
(define (problem ferry-01)
 (:domain ferry)
 (:objects 
    car1 car2 car3 car4 car5 car6 - car
    loc1 loc2 loc3 loc4 loc5 - location
 )
 (:init 
    (empty-ferry)
    (at-ferry loc1)
    (at-ferry loc2)
    (at-ferry loc3)
    (at-ferry loc4)
    (at-ferry loc5)
    (not-at-ferry loc1)
    (not-at-ferry loc2)
    (not-at-ferry loc3)
    (not-at-ferry loc4)
    (not-at-ferry loc5)
    (on car1)
    (on car2)
    (on car3)
    (on car4)
    (on car5)
    (on car6)
    (at car1 loc1)
    (at car2 loc1)
    (at car3 loc1)
    (at car4 loc1)
    (at car5 loc1)
    (at car6 loc1)
    (at car1 loc2)
    (at car2 loc2)
    (at car3 loc2)
    (at car4 loc2)
    (at car5 loc2)
    (at car6 loc2)
    (at car1 loc3)
    (at car2 loc3)
    (at car3 loc3)
    (at car4 loc3)
    (at car5 loc3)
    (at car6 loc3)
    (at car1 loc4)
    (at car2 loc4)
    (at car3 loc4)
    (at car4 loc4)
    (at car5 loc4)
    (at car6 loc4)
    (at car1 loc5)
    (at car2 loc5)
    (at car3 loc5)
    (at car4 loc5)
    (at car5 loc5)
    (at car6 loc5)
    (eq loc1 loc1)
    (eq loc2 loc2)
    (eq loc3 loc3)
    (eq loc4 loc4)
    (eq loc5 loc5)
)
 (:goal  (and (at car1 loc3)
    (at car2 loc3))))
