(define (problem gripper-7-4-3)
(:domain gripper-strips)
(:objects  left middle right ball1 ball2 ball3 ball4 ball5 ball6 rooma roomb roomc roomd)
(:init
(room rooma)
(room roomb)
(room roomc)
(room roomd)
(gripper left)
(gripper middle)
(gripper right)
(ball ball1)
(ball ball2)
(ball ball3)
(ball ball4)
(ball ball5)
(ball ball6)
(free left)
(free middle)
(free right)
(at ball1 rooma)
(at ball2 rooma)
(at ball3 rooma)
(at ball4 roomb)
(at ball5 roomb)
(at ball6 rooma)
(at-robby rooma)
(eq rooma rooma)
(eq roomb roomb)
(eq roomc roomc)
(eq roomd roomd)
)
(:goal
(and
(at ball1 roomb)
(at ball2 roomb)
(at ball3 roomb)
)
)
)
