(define (problem gripper-7-4-3)
(:domain gripper-strips)
(:objects  left middle right ball1 ball2 ball3 ball4 ball5 ball6 ball7 rooma roomb roomc roomd)
(:init
(room rooma)
(room roomb)
(room roomc)
(room roomd)
(gripper left)
(gripper middle)
(gripper right)
(ball ball1)
(ball ball2)
(ball ball3)
(ball ball4)
(ball ball5)
(ball ball6)
(ball ball7)
(free left)
(free middle)
(free right)
(at ball1 rooma)
(at ball2 rooma)
(at ball3 rooma)
(at ball4 rooma)
(at ball5 rooma)
(at ball6 rooma)
(at ball7 rooma)
(at ball1 roomb)
(at ball2 roomb)
(at ball3 roomb)
(at ball4 roomb)
(at ball5 roomb)
(at ball6 roomb)
(at ball7 roomb)
(at ball1 roomc)
(at ball2 roomc)
(at ball3 roomc)
(at ball4 roomc)
(at ball5 roomc)
(at ball6 roomc)
(at ball7 roomc)
(at ball1 roomd)
(at ball2 roomd)
(at ball3 roomd)
(at ball4 roomd)
(at ball5 roomd)
(at ball6 roomd)
(at ball7 roomd)
(at-robby rooma)
(at-robby roomb)
(at-robby roomc)
(at-robby roomd)
(carry ball1 left)
(carry ball2 left)
(carry ball3 left)
(carry ball4 left)
(carry ball5 left)
(carry ball6 left)
(carry ball7 left)
(carry ball1 middle)
(carry ball2 middle)
(carry ball3 middle)
(carry ball4 middle)
(carry ball5 middle)
(carry ball6 middle)
(carry ball7 middle)
(carry ball1 right)
(carry ball2 right)
(carry ball3 right)
(carry ball4 right)
(carry ball5 right)
(carry ball6 right)
(carry ball7 right)
(eq rooma rooma)
(eq roomb roomb)
(eq roomc roomc)
(eq roomd roomd)
)
(:goal
(and
(at ball1 roomb)
(at ball2 roomb)
(at ball3 roomb)
)
)
)
