(define (problem BLOCKS-5-0)
(:domain BLOCKS)
(:objects E D B A C F G H - block)
(:init  (clear A)
        (clear B)
        (clear C)
        (clear D)
        (clear E)
        (clear F)
        (clear G)
        (clear H)
        (ontable A)
        (ontable B)
        (ontable C)
        (ontable D)
        (ontable E)
        (ontable F)
        (ontable G)
        (ontable H)
        (on A A)
        (on B A)
        (on C A)
        (on D A)
        (on E A)
        (on F A)
        (on G A)
        (on H A)
        (on A B)
        (on B B)
        (on C B)
        (on D B)
        (on E B)
        (on F B)
        (on G B)
        (on H B)
        (on A C)
        (on B C)
        (on C C)
        (on D C)
        (on E C)
        (on F C)
        (on G C)
        (on H C)
        (on A D)
        (on B D)
        (on C D)
        (on D D)
        (on E D)
        (on F D)
        (on G D)
        (on H D)
        (on A E)
        (on B E)
        (on C E)
        (on D E)
        (on E E)
        (on F E)
        (on G E)
        (on H E)
        (on A F)
        (on B F)
        (on C F)
        (on D F)
        (on E F)
        (on F F)
        (on G F)
        (on H F)
        (on A G)
        (on B G)
        (on C G)
        (on D G)
        (on E G)
        (on F G)
        (on G G)
        (on H G)
        (on A H)
        (on B H)
        (on C H)
        (on D H)
        (on E H)
        (on F H)
        (on G H)
        (on H H)
        (holding A)
        (holding B)
        (holding C)
        (holding D)
        (holding E)
        (holding F)
        (holding G)
        (holding H)
        (handempty))
(:goal (and (on E D) (on D C) (on C B) (on B A)))
)
