(define (problem miconic3x2)
	(:domain miconic)
	(:objects floor1 floor2 floor3 floor4 floor5 floor6 person1 person2 person3 person4 person5 person6)
	(:init (above floor1 floor2)
		(above floor2 floor3)
		(above floor3 floor4)
		(above floor4 floor5)
		(above floor5 floor6)
		(lift_pos floor1)
		(lift_pos floor2)
		(lift_pos floor3)
		(lift_pos floor4)
		(lift_pos floor5)
		(lift_pos floor6)
		(lift_pos person1)
		(lift_pos person2)
		(lift_pos person3)
		(lift_pos person4)
		(lift_pos person5)
		(lift_pos person6)
		(floor floor1)
		(floor floor2)
		(floor floor3)
		(floor floor4)
		(floor floor5)
		(floor floor6)
		(person person1)
		(person person2)
		(person person3)
		(person person4)
        (person person5)
		(person person6)
		(in_lift person1)
		(in_lift person2)
		(in_lift person3)
		(in_lift person4)
		(in_lift person5)
		(in_lift person6)
		(in_lift floor1)
		(in_lift floor2)
		(in_lift floor3)
		(in_lift floor4)
		(in_lift floor5)
		(in_lift floor6)
		(in_floor person1 floor1)
		(in_floor person2 floor1)
		(in_floor person3 floor1)
		(in_floor person4 floor1)
		(in_floor person5 floor1)
		(in_floor person6 floor1)
		(in_floor person1 floor2)
		(in_floor person2 floor2)
		(in_floor person3 floor2)
		(in_floor person4 floor2)
		(in_floor person5 floor2)
		(in_floor person6 floor2)
		(in_floor person1 floor3)
		(in_floor person2 floor3)
		(in_floor person3 floor3)
		(in_floor person4 floor3)
		(in_floor person5 floor3)
		(in_floor person6 floor3)
		(in_floor person1 floor4)
		(in_floor person2 floor4)
		(in_floor person3 floor4)
		(in_floor person4 floor4)
		(in_floor person5 floor4)
		(in_floor person6 floor4)
		(in_floor person1 floor5)
		(in_floor person2 floor5)
		(in_floor person3 floor5)
		(in_floor person4 floor5)
		(in_floor person5 floor5)
		(in_floor person6 floor5)
		(in_floor person1 floor6)
		(in_floor person2 floor6)
		(in_floor person3 floor6)
		(in_floor person4 floor6)
		(in_floor person5 floor6)
		(in_floor person6 floor6)
		(in_floor floor1 floor1)
		(in_floor floor2 floor1)
		(in_floor floor3 floor1)
		(in_floor floor4 floor1)
		(in_floor floor5 floor1)
		(in_floor floor6 floor1)
		(in_floor floor1 floor2)
		(in_floor floor2 floor2)
		(in_floor floor3 floor2)
		(in_floor floor4 floor2)
		(in_floor floor5 floor2)
		(in_floor floor6 floor2)
		(in_floor floor1 floor3)
		(in_floor floor2 floor3)
		(in_floor floor3 floor3)
		(in_floor floor4 floor3)
		(in_floor floor5 floor3)
		(in_floor floor6 floor3)
		(in_floor floor1 floor4)
		(in_floor floor2 floor4)
		(in_floor floor3 floor4)
		(in_floor floor4 floor4)
		(in_floor floor5 floor4)
		(in_floor floor6 floor4)
		(in_floor floor1 floor5)
		(in_floor floor2 floor5)
		(in_floor floor3 floor5)
		(in_floor floor4 floor5)
		(in_floor floor5 floor5)
		(in_floor floor6 floor5)
		(in_floor floor1 floor6)
		(in_floor floor2 floor6)
		(in_floor floor3 floor6)
		(in_floor floor4 floor6)
		(in_floor floor5 floor6)
		(in_floor floor6 floor6)
		(in_floor person1 person1)
		(in_floor person2 person1)
		(in_floor person3 person1)
		(in_floor person4 person1)
		(in_floor person5 person1)
		(in_floor person6 person1)
		(in_floor person1 person2)
		(in_floor person2 person2)
		(in_floor person3 person2)
		(in_floor person4 person2)
		(in_floor person5 person2)
		(in_floor person6 person2)
		(in_floor person1 person3)
		(in_floor person2 person3)
		(in_floor person3 person3)
		(in_floor person4 person3)
		(in_floor person5 person3)
		(in_floor person6 person3)
		(in_floor person1 person4)
		(in_floor person2 person4)
		(in_floor person3 person4)
		(in_floor person4 person4)
		(in_floor person5 person4)
		(in_floor person6 person4)
		(in_floor person1 person5)
		(in_floor person2 person5)
		(in_floor person3 person5)
		(in_floor person4 person5)
		(in_floor person5 person5)
		(in_floor person6 person5)
		(in_floor person1 person6)
		(in_floor person2 person6)
		(in_floor person3 person6)
		(in_floor person4 person6)
		(in_floor person5 person6)
		(in_floor person6 person6)
		(in_floor floor1 person1)
		(in_floor floor2 person1)
		(in_floor floor3 person1)
		(in_floor floor4 person1)
		(in_floor floor5 person1)
		(in_floor floor6 person1)
		(in_floor floor1 person2)
		(in_floor floor2 person2)
		(in_floor floor3 person2)
		(in_floor floor4 person2)
		(in_floor floor5 person2)
		(in_floor floor6 person2)
		(in_floor floor1 person3)
		(in_floor floor2 person3)
		(in_floor floor3 person3)
		(in_floor floor4 person3)
		(in_floor floor5 person3)
		(in_floor floor6 person3)
		(in_floor floor1 person4)
		(in_floor floor2 person4)
		(in_floor floor3 person4)
		(in_floor floor4 person4)
		(in_floor floor5 person4)
		(in_floor floor6 person4)
		(in_floor floor1 person5)
		(in_floor floor2 person5)
		(in_floor floor3 person5)
		(in_floor floor4 person5)
		(in_floor floor5 person5)
		(in_floor floor6 person5)
		(in_floor floor1 person6)
		(in_floor floor2 person6)
		(in_floor floor3 person6)
		(in_floor floor4 person6)
		(in_floor floor5 person6)
		(in_floor floor6 person6))
	(:goal (and (in_floor person1 floor2)
		(in_floor person2 floor3))))
